#! .venv/bin/python

import os
import site;
import yaml

venvSitePackage       = site.getsitepackages()[0]
venvContextLangServer = os.path.join(venvSitePackage, 'contextLangServer' )
#print(venvContextLangServer)

os.system(f"rm -rf {venvContextLangServer}")
os.system(f"cp -r ../conTeXt-langServer/contextLangServer {venvSitePackage}")
