#! .venv/bin/python

import os
import site;
import yaml

venvSitePackage = site.getsitepackages()[0]
venvLpicSyntaxes = os.path.join(venvSitePackage, 'lpicSyntaxes' )
#print(venvLpicSyntaxes)

os.system(f"rm -rf {venvLpicSyntaxes}")
os.system(f"cp -r ../lpic-syntaxes/lpicSyntaxes {venvSitePackage}")
